In [23]:
import numpy as np
x = np.array([13, 10])
y = np.array([12, 15])
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Comparison - greater
[ True False]
Comparison - greater_equal
[ True False]
Comparison - less
[False  True]
Comparison - less_equal
[False  True]


In [24]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
import numpy as np
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [26]:
import numpy as np
x=np.array([1,1])
y=np.array([2,2])
print("Add:")
print(np.add(x,y))
print("Subtract:")
print(np.subtract(x,y))
print("Multiply:")
print(np.multiply(x,y))
print("Divide:")
print(np.divide(x,y))

Add:
[3 3]
Subtract:
[-1 -1]
Multiply:
[2 2]
Divide:
[0.5 0.5]


In [42]:
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0, 30, 45, 60, 90))* np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0, 30, 45, 60, 90))* np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0, 30, 45, 60, 90))* np.pi / 180. ))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [54]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [62]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['sai', 'kiran', 'mno', 'abc', 'xyz', 'dharshan', 'basa', 'april', 'march', 'monday'],
              'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
              'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
              'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print("Data")
print(df[['name', 'score','attempts','qualify']])

Data
       name  score  attempts qualify
a       sai   12.5         1     yes
b     kiran    9.0         3      no
c       mno   16.5         2     yes
d       abc    NaN         3      no
e       xyz    9.0         2      no
f  dharshan   20.0         3     yes
g      basa   14.5         1     yes
h     april    NaN         1      no
i     march    8.0         2      no
j    monday   19.0         1     yes


In [66]:
import pandas as pd

student_data1 = pd.DataFrame({
        'student_id': ['1', '2', '3', '4', '5'],
         'name': ['Prince', 'Archi', 'Prashya', 'Sallya', 'Pradeep'], 
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['4', '5', '6', '7', '8'],
        'name': ['Atharva', 'Manoj', 'Shubham', 'Saikiran', 'Rushikesh'], 
        'marks': [201, 200, 198, 219, 201]})

print("Original DataFrames:")
print(student_data1)
print(student_data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([student_data1, student_data2])
print(result_data)


Original DataFrames:
  student_id     name  marks
0          1   Prince    200
1          2    Archi    210
2          3  Prashya    190
3          4   Sallya    222
4          5  Pradeep    199
  student_id       name  marks
0          4    Atharva    201
1          5      Manoj    200
2          6    Shubham    198
3          7   Saikiran    219
4          8  Rushikesh    201

Join the said two dataframes along rows:
  student_id       name  marks
0          1     Prince    200
1          2      Archi    210
2          3    Prashya    190
3          4     Sallya    222
4          5    Pradeep    199
0          4    Atharva    201
1          5      Manoj    200
2          6    Shubham    198
3          7   Saikiran    219
4          8  Rushikesh    201


In [68]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
df = pd.DataFrame({
'student_id':[70001,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'fees_amount':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'add_date': ['2012-10-05','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'libaray_id':[3002,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001],
'workshop_id':[5002,5003,5001,np.nan,5002,5001,5001,np.nan,5003,5002,5003,np.nan]})
print("Original Orders DataFrame:")
print(df)
print("\nMissing values of the said dataframe:")
print(df.isna())

Original Orders DataFrame:
    student_id  fees_amount    add_date  libaray_id  workshop_id
0      70001.0       150.50  2012-10-05        3002       5002.0
1          NaN       270.65  2012-09-10        3001       5003.0
2      70002.0        65.26         NaN        3001       5001.0
3      70004.0       110.50  2012-08-17        3003          NaN
4          NaN       948.50  2012-09-10        3002       5002.0
5      70005.0      2400.60  2012-07-27        3001       5001.0
6          NaN      5760.00  2012-09-10        3001       5001.0
7      70010.0      1983.43  2012-10-10        3004          NaN
8      70003.0      2480.40  2012-10-10        3003       5003.0
9      70012.0       250.45  2012-06-27        3002       5002.0
10         NaN        75.29  2012-08-17        3001       5003.0
11     70013.0      3045.60  2012-04-25        3001          NaN

Missing values of the said dataframe:
    student_id  fees_amount  add_date  libaray_id  workshop_id
0        False        Fals

In [70]:
import pandas as pd
ds = pd.Series([26,84,97,22,84,65,55,])
print(ds)

0    26
1    84
2    97
3    22
4    84
5    65
6    55
dtype: int64
